concurrency:
  cancel-in-progress: true
  group: prodbuild
jobs:
  build:
    environment: container-registry
    permissions:
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: "actions/checkout@v3"
      - name: setup qemu for docker
        uses: "docker/setup-qemu-action@v2"
      - name: setup docker buildx
        uses: "docker/setup-buildx-action@v2"
      - name: setup cache for docker layers
        uses: "actions/cache@v4"
        with:
          key: "dockercache:${{ runner.os }}:${{ github.sha }}"
          path: /tmp/.buildx-cache
          restore-keys: "dockercache:${{ runner.os }}:"
      - name: login ghcr.io
        uses: "docker/login-action@v2"
        with:
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: ghcr.io
          username: "${{ github.actor }}"
      - name: "build and push (runner)"
        uses: "docker/build-push-action@v4"
        with:
          cache-from: "type=local,src=/tmp/.buildx-cache"
          cache-to: "type=local,dest=/tmp/.buildx-cache-new"
          context: '.'
          file: "./Dockerfile"
          platforms: "linux/amd64,linux/arm64"
          push: true
          tags: ghcr.io/pctg-x8/lunarlight:latest
          target: runner
      - name: "build and push (managetools)"
        uses: "docker/build-push-action@v4"
        with:
          cache-from: "type=local,src=/tmp/.buildx-cache"
          cache-to: "type=local,dest=/tmp/.buildx-cache-new"
          context: '.'
          file: "./Dockerfile"
          platforms: "linux/amd64,linux/arm64"
          push: true
          tags: ghcr.io/pctg-x8/lunarlight/managetools:latest
          target: managetools
      - name: "build and push (streamer)"
        uses: "docker/build-push-action@v4"
        with:
          cache-from: "type=local,src=/tmp/.buildx-cache"
          cache-to: "type=local,dest=/tmp/.buildx-cache-new"
          context: '.'
          file: "./Dockerfile"
          platforms: "linux/amd64,linux/arm64"
          push: true
          tags: ghcr.io/pctg-x8/lunarlight/streamer:latest
          target: streamer
      - name: replace all docker layer caches
        run: "rm -rf /tmp/.buildx-cache && mv /tmp/.buildx-cache-new /tmp/.buildx-cache"
  replaceContainer:
    environment: prod
    needs:
      - build
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: "aws-actions/configure-aws-credentials@v1"
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::208140986057:role/crescent/lunarlight/auto-deployment-role
      - name: run replace command
        run: |
          set -e
          
          commandId=$(aws ssm send-command --document-name "Crescent-Lunarlight-DeploymentContainers" --document-version "\$LATEST" --targets '[{"Key":"InstanceIds","Values":["i-0195ecc0d1e95f81e"]}]' --parameters '{}' --timeout-seconds 600 --max-concurrency "50" --max-errors "0" --cloud-watch-output-config '{"CloudWatchOutputEnabled":false}' --region ap-northeast-1 --output text --query 'Command.CommandId')
          aws ssm wait command-executed --command-id $commandId --instance-id i-0195ecc0d1e95f81e
name: deploy
on:
  push:
    branches:
      - main
